name: "Feature request / PRD"
description: "Propose a new feature and attach a PRD"
title: "[Feature] <short summary>"
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please provide a succinct PRD or link to `docs/product/PRD.md`.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      placeholder: What problem are we solving?
    validations:
      required: true
  - type: textarea
    id: goals
    attributes:
      label: Goals / Non-goals
  - type: textarea
    id: requirements
    attributes:
      label: Requirements / Acceptance criteria
  - type: textarea
    id: design
    attributes:
      label: Proposed approach / design
  - type: textarea
    id: prd_link
    attributes:
      label: PRD link
      description: Link to PRD in repo (e.g., `/docs/product/PRD.md`).
